version: '3'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./db_data:/data
    ports:
      - "5432:5432"
    environment:
      PGDATA: /data
      POSTGRES_DB: backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
  db_nosql_redis:
    image: redis:alpine
    volumes:
      - ./db_data:/redis
    ports:
      - "6379:6379"